language: ruby
rvm:
- 2.1
sudo: false
addons:
  apt:
    packages:
    - pkg-config
script:
  - bundle exec rake test
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
